"""Validate the reviewed REST ledger and generate its human-readable report.

This is a review guard, not a Rust parser or proof of behavioral conformance.
Changed source files require targeted review and explicit acknowledgement.
Run from any directory; the default is a read-only check.
"""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
LEDGER = ROOT / "spec/api-coverage.json"
REPORT = ROOT / "spec/api-coverage.md"
STATES = {"implemented", "partial", "stub", "missing", "excluded"}
METHODS = {"GET", "POST", "PUT", "PATCH", "DELETE"}


def normalize(path: str) -> str:
    return re.sub(r"\{[^}]+\}", "{id}", path.rstrip("/"))


def expand(path: str) -> list[str]:
    """Expand compact table notation, including optional /{id} suffixes."""
    optional = re.search(r"\[([^]]+)\]", path)
    if optional:
        before, after = path[:optional.start()], path[optional.end():]
        return expand(before + after) + expand(before + optional[1] + after)
    choices = re.search(r"\{([^}]*,[^}]*)\}", path)
    if choices:
        return [p for value in choices[1].split(",")
                for p in expand(path[:choices.start()] + value + path[choices.end():])]
    return [normalize(path)]


def reference_endpoints(repo: Path) -> set[str]:
    """Read the reference without importing or starting the Python server."""
    schema = json.loads((repo / "mastodon-openapi/dist/schema.json").read_text(encoding="utf-8"))
    result = {f"{method.upper()} {normalize(path)}" for path, ops in schema["paths"].items()
              for method in ops if method.upper() in METHODS}
    for line in (repo / "spec/03-api-coverage.md").read_text(encoding="utf-8").splitlines():
        cols = line.split("|")
        if len(cols) < 4 or not re.fullmatch(r"\s*(GET|POST|PUT|PATCH|DELETE)(\s*/\s*(GET|POST|PUT|PATCH|DELETE))*\s*", cols[1]):
            continue
        for path in re.findall(r"`(/[^`?]+)(?:[^`]*)`", cols[2]):
            if "_mock" not in path:
                result.update(f"{method} {p}" for p in expand(path)
                              for method in re.findall(r"GET|POST|PUT|PATCH|DELETE", cols[1]))
    return result


def fingerprints(root: Path = ROOT) -> dict[str, str]:
    """Normalize line endings so Windows checkout settings do not cause drift."""
    src = root / "mastomini_rs/src"
    files = set(src.glob("api/*.rs")) | set(src.glob("domain/*.rs"))
    files |= {src / name for name in ("http.rs", "auth.rs", "crypto.rs", "text.rs", "codec.rs", "store/mod.rs")}
    files = {p for p in files if p.stem not in {"tests", "testkit"}}
    return {p.relative_to(root).as_posix(): hashlib.sha256(p.read_text(encoding="utf-8").encode()).hexdigest()
            for p in sorted(files)}


def validate(data: dict, current: dict[str, str], root: Path = ROOT) -> list[str]:
    errors: list[str] = []
    keys: set[str] = set()
    for row in data["endpoints"]:
        key = f'{row["method"]} {row["path"]}'
        if key in keys:
            errors.append(f"Duplicate: {key}")
        keys.add(key)
        if row["method"] not in METHODS or row["status"] not in STATES or row["tier"] not in (1, 2, 3):
            errors.append(f"Invalid classification: {key}")
        if row["path"] != normalize(row["path"]) or not row["path"].startswith("/"):
            errors.append(f"Noncanonical path: {key}")
        if not row["note"] or not (root / row["source"]).is_file():
            errors.append(f"Missing explanation or evidence file: {key}")
    for key in sorted(set(data["reference_endpoints"]) - keys):
        errors.append(f"Unclassified reference endpoint: {key}")
    reviewed = data["reviewed_sources"]
    for path in sorted(current.keys() | reviewed.keys()):
        if current.get(path) != reviewed.get(path):
            errors.append(f"Review changed source: {path}")
    return errors


def render(data: dict) -> str:
    rows = data["endpoints"]
    counts = Counter(r["status"] for r in rows)
    out = ["# REST endpoint coverage", "",
           "Generated by `mastomini_rs/scripts/api-coverage.py --write` from [api-coverage.json](api-coverage.json).",
           "See [maintenance and priorities](api-audit.md) before updating classifications.", "",
           "Scope: pinned mastodon_mock OpenAPI + its REST checklist + mastomini's additional routes.",
           "This includes versions newer than advertised 4.3. It is not a claim of complete Mastodon parity.",
           "Path parameter names are normalized to `{id}` (including names, tags and group keys).", "",
           f"**{len(rows)} method/path pairs:** " + ", ".join(f"{counts[s]} {s}" for s in sorted(STATES)) + ".", "",
           "`implemented` means a substantive local handler, not certification of every parameter;",
           "`partial` has explicit behavioral limits; `stub` is a neutral/no-op handler;",
           "`missing` is unimplemented backlog; `excluded` is an intentional v1 omission (possibly a neutral handler).", ""]
    for tier in (1, 2, 3):
        out += [f"## Tier {tier}", "", "| Method | Path | State | Evidence | Behavior / gap |",
                "|---|---|---|---|---|"]
        for row in sorted((r for r in rows if r["tier"] == tier), key=lambda r: (r["path"], r["method"])):
            source = row["source"]
            out.append(f'| {row["method"]} | `{row["path"]}` | **{row["status"]}** | [{Path(source).name}](../{source}) | {row["note"].replace("|", "/")} |')
        out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate Markdown; does not acknowledge source drift")
    parser.add_argument("--acknowledge", action="append", default=[], metavar="REPO_RELATIVE_FILE",
                        help="After reviewing this file's endpoint/semantic changes, record its current hash")
    parser.add_argument("--reference", type=Path, help="Also compare the snapshot with a mastodon_mock checkout")
    args = parser.parse_args()
    data = json.loads(LEDGER.read_text(encoding="utf-8"))
    current = fingerprints()
    for path in args.acknowledge:
        if path not in current and path not in data["reviewed_sources"]:
            parser.error(f"Not a monitored implementation file: {path}")
        if path in current:
            data["reviewed_sources"][path] = current[path]
        else:
            data["reviewed_sources"].pop(path)
    if args.acknowledge:
        LEDGER.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    errors = validate(data, current)
    if args.reference:
        reference = reference_endpoints(args.reference)
        snapshot = set(data["reference_endpoints"])
        errors += [f"New reference endpoint; classify and add to snapshot: {k}" for k in sorted(reference - snapshot)]
        errors += [f"Removed reference endpoint; review snapshot: {k}" for k in sorted(snapshot - reference)]
    report = render(data)
    if args.write:
        REPORT.write_text(report, encoding="utf-8")
    elif not REPORT.exists() or REPORT.read_text(encoding="utf-8") != report:
        errors.append("Coverage report is stale; run with --write")
    if errors:
        print("\n".join(errors))
        return 1
    print(f'Coverage ledger checked: {len(data["endpoints"])} endpoints, {len(current)} reviewed source files.')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
