//! Name restrictions matching the household CA generated by certs.sh.
//! mbedTLS lacks nameConstraints support, so the board enforces this exact
//! supported extension on household connections and every certificate SAN.
use std::net::Ipv4Addr;

const DNS: [&str; 5] = ["local", "localhost", "lan", "home.arpa", "internal"];
const NETWORKS: [[u8; 8]; 4] = [
    [10, 0, 0, 0, 255, 0, 0, 0],
    [172, 16, 0, 0, 255, 240, 0, 0],
    [192, 168, 0, 0, 255, 255, 0, 0],
    [127, 0, 0, 0, 255, 0, 0, 0],
];

fn dns_allowed(name: &[u8]) -> bool {
    let Ok(name) = std::str::from_utf8(name) else {
        return false;
    };
    let name = name.to_ascii_lowercase();
    DNS.iter()
        .any(|base| name == *base || name.ends_with(&format!(".{base}")))
}

fn ip_allowed(ip: &[u8]) -> bool {
    ip.len() == 4
        && NETWORKS
            .iter()
            .any(|net| (0..4).all(|i| ip[i] & net[i + 4] == net[i]))
}

pub fn household_host(host: &str) -> bool {
    host.parse::<Ipv4Addr>().map_or_else(
        |_| dns_allowed(host.as_bytes()),
        |ip| ip_allowed(&ip.octets()),
    )
}

/// DNS and IP constraints apply to every SAN, not just the name requested.
pub fn san_allowed(tag: i32, value: &[u8]) -> bool {
    match tag & 0x1f {
        // mbedTLS classifies SANs with the tag number. Reject malformed
        // constructed DNS/IP encodings rather than treating them as another
        // unconstrained name type.
        2 => tag == 0x82 && dns_allowed(value),
        7 => tag == 0x87 && ip_allowed(value),
        _ => true, // The CA does not constrain other GeneralName types.
    }
}

/// Exact DER for the supported critical extension. Any changed constraints
/// (including added exclusions or narrower ranges) fail closed at parsing.
pub fn constraints_der() -> Vec<u8> {
    let mut subtrees = Vec::new();
    for name in DNS {
        subtrees.extend([0x30, (name.len() + 2) as u8, 0x82, name.len() as u8]);
        subtrees.extend(name.bytes());
    }
    for net in NETWORKS {
        subtrees.extend([0x30, 10, 0x87, 8]);
        subtrees.extend(net);
    }
    let mut der = vec![0x30, (subtrees.len() + 2) as u8, 0xa0, subtrees.len() as u8];
    der.extend(subtrees);
    der
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn household_anchor_cannot_authenticate_public_hosts_or_outside_sans() {
        for host in [
            "mastomini.local",
            "MASTOMINI.LOCAL",
            "x.home.arpa",
            "192.168.1.161",
            "172.31.255.255",
            "127.0.0.1",
        ] {
            assert!(household_host(host), "{host}");
        }
        for host in [
            "openrouter.ai",
            "local.evil.com",
            "notlocal",
            "172.32.0.1",
            "169.254.1.1",
            "8.8.8.8",
        ] {
            assert!(!household_host(host), "{host}");
        }
        assert!(san_allowed(0x82, b"*.home.arpa"));
        assert!(!san_allowed(0x82, b"evil.com"));
        assert!(san_allowed(0x87, &[192, 168, 1, 161]));
        assert!(!san_allowed(0x87, &[8, 8, 8, 8]));
        assert!(!san_allowed(0x87, &[0; 16]));
        assert!(!san_allowed(0xa2, b"evil.com"));
        assert!(!san_allowed(0xa2, b"mastomini.local"));
        assert!(!san_allowed(0xa7, &[8, 8, 8, 8]));
    }

    #[test]
    fn supported_constraints_match_openssl_extension_fixture() {
        // Extracted from OpenSSL's encoding of certs.sh's nameConstraints.
        // Keep desktop tests independent of a developer's private certs/ dir.
        let extension = include_bytes!("../tests/fixtures/household-name-constraints.der");
        assert_eq!(constraints_der(), extension);
    }
}
